# Generated by Django 3.1.2 on 2020-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильтра')),
                ('year_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='Год с')),
                ('year_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Год до')),
                ('price_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена с')),
                ('price_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена до')),
                ('body', models.CharField(choices=[('clear', 'не указывать'), ('sedan', 'седан'), ('station-wagon', 'универсал'), ('hatchback', 'хэтчбек'), ('limousine', 'лимузин'), ('body-coupe', 'купе'), ('body-roadster', 'родстер'), ('cabriolet', 'кабриолет'), ('suv', 'внедорожник'), ('crossover-suv', 'внедорожник'), ('microvan', 'микровэн'), ('minivan', 'минивэн'), ('van', 'микроавтобус'), ('wagon', 'фургон'), ('body-pickup', 'пикап'), ('targa', 'тарга'), ('fastback', 'фастбек'), ('liftback', 'лифтбек'), ('hardtop', 'хардтоп')], default='sedan', max_length=120, verbose_name='Кузов')),
                ('engine_fuel', models.CharField(choices=[('clear', 'не указывать'), ('1', 'бензин'), ('2', 'дизель'), ('3', 'газ-бензин'), ('4', 'газ'), ('5', 'гибрид'), ('6', 'электричество')], default='1', max_length=120, verbose_name='Тип двигателя')),
                ('transmission_type', models.CharField(choices=[('clear', 'не указывать'), ('1', 'механика'), ('2', 'АКПП'), ('3', 'автомат'), ('4', 'типтроник'), ('5', 'вариатор'), ('6', 'робот')], default='1', max_length=120, verbose_name='КПП')),
                ('engine_volume_from', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Объем двигателя от')),
                ('engine_volume_to', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Объем двигателя до')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст поиска')),
                ('url', models.CharField(default='https://kolesa.kz/cars/', max_length=1000, verbose_name='Сслыка поиска')),
                ('lastcar', models.CharField(default=1, max_length=100, verbose_name='lastacar id')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
    ]
