# Generated by Django 3.1.1 on 2020-11-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='cheaper_perc',
            field=models.CharField(choices=[('15', '15%'), ('20', '20%'), ('25', '25%'), ('30', '30%')], default=1, max_length=100, verbose_name='Дешевле на'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='view_count',
            field=models.PositiveIntegerField(default='1', verbose_name='Кол. просмотров'),
        ),
    ]
