# Generated by Django 4.2.9 on 2024-01-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_filter_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='city',
        ),
    ]
