# Generated by Django 4.2.9 on 2024-01-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_cars', to='handler.filter'),
            preserve_default=False,
        ),
    ]
