# Generated by Django 4.2.9 on 2024-01-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0007_car_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
